// Generated by CoffeeScript 1.10.0
(function() {
  var i, item, len, list;

  list = ["cat", "dog", "fish", "guinea pig"];

  for (i = 0, len = list.length; i < len; i++) {
    item = list[i];
    console.log(item);
  }

}).call(this);
