// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  $(function() {
    var ListView, Task, TaskCollection, TaskView, list;
    Task = (function(superClass) {
      extend(Task, superClass);

      function Task() {
        return Task.__super__.constructor.apply(this, arguments);
      }

      Task.prototype.defaults = function() {
        return {
          finished: false,
          text: ""
        };
      };

      return Task;

    })(Backbone.Model);
    TaskCollection = (function(superClass) {
      extend(TaskCollection, superClass);

      function TaskCollection() {
        return TaskCollection.__super__.constructor.apply(this, arguments);
      }

      TaskCollection.prototype.model = Task;

      return TaskCollection;

    })(Backbone.Collection);
    TaskView = (function(superClass) {
      extend(TaskView, superClass);

      function TaskView() {
        return TaskView.__super__.constructor.apply(this, arguments);
      }

      TaskView.prototype.tagName = "li";

      TaskView.prototype.render = function() {
        $(this.el).html("<span>" + (this.model.get('text')) + ". Complete? " + (this.model.get('finished')) + ".</span>");
        return this;
      };

      return TaskView;

    })(Backbone.View);
    ListView = (function(superClass) {
      extend(ListView, superClass);

      function ListView() {
        return ListView.__super__.constructor.apply(this, arguments);
      }

      ListView.prototype.el = $("body");

      ListView.prototype.initialize = function() {
        this.collection = new TaskCollection;
        this.collection.bind("add", this.appendItem);
        this.counter = 0;
        return this.render();
      };

      ListView.prototype.render = function() {
        $(this.el).append("<button>Add List Item</button>");
        return $(this.el).append("<ul></ul>");
      };

      ListView.prototype.addItem = function() {
        var task;
        this.counter++;
        task = new Task;
        task.set({
          text: "Hi " + this.counter
        });
        return this.collection.add(task);
      };

      ListView.prototype.appendItem = function(task) {
        var task_view;
        task_view = new TaskView({
          model: task
        });
        return $("ul").append(task_view.render().el);
      };

      ListView.prototype.events = {
        "click button": "addItem"
      };

      return ListView;

    })(Backbone.View);
    return list = new ListView;
  });

}).call(this);
